SUSE/libpulp

Makefile.common
tests/Makefile.am
tests/syscall_restart.c
tests/syscall_restart.py
tests/thread_restore.py
tools/introspection.c
tools/ulp.c

There are multiple topics in this merge request, notably, a fix for thread context restoration and explanations about the transparency of syscall restarting by the kernel. Each contain a new test case. (see commit messages for explanations).

Thread restoration and syscall restarting

---

Makefile.am
configure.ac
tools/Makefile.am
tools/check.c
tools/introspection.c
tools/introspection.h
tools/trigger.c

With these patches binutils-devel is no longer required and make check will not finish successfully if it didn't test anything.

Avoid libbfd

---

include/ulp.h
lib/ulp.c
tests/Makefile.am
tests/libaddress.c
tests/libaddress.h
tests/libaddress_livepatch1.c
tests/libaddress_livepatch1.in
tests/memory_protection.c
tests/memory_protection.py

None of the examples I have built so far will be affected by this change, because the memory protection bits for code segments in all of them are always set to read and execute (the default that libpulp restores to). However, it is theoretically possible that applications change the protection configuration of their own memory, so this patch makes live patching more transparent.

Restore previous memory protection bits after live patching

---

Makefile.common
README.md
include/ulp_common.h
lib/ulp.c
man/libpulp.7
tests/Makefile.am
tests/access.c
tests/access.py
tests/libaccess.c
tests/libaccess.h
tests/libaccess_livepatch1.c
tests/libaccess_livepatch1.in
tests/offsets.py
tools/packer.c

Read the commit message for more information...
Apart from that, the patch adds new information to the live patch metadata, more specifically, the addresses (offsets from the load address) of data objects, and that means that there is no need to open in-disk files (DSOs) during live patch application to fix references to LOCAL objects.
We should probably copy this mechanism to the other parts of the live patch metadata, so that, in the future, nothing else depends on the target library file being both in-disk and in the exact same version that the target process used (which doesn´t work after package updates).

Add support for unexported variables access in live patches

---

bootstrap

The `boostrap` only runs the necessary commands in order to generate
the `configure` script, but do not check if the user indeed have the
necessary files installed. This commit fixes that by checking if
every command can be run before executing the bootstrap process, and
on failure display a single message showing which command has failed.

Ensure bootstrap check if user has requirements

---

configure.ac

If a C++ compiler is not present, configure defaults it to g++ even if
it is not there. This commit fixes that. Fixes #41.
Original error message:
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../libpulp/tests \
-I../include -fPIC -fpatchable-function-entry=24,22 -fno-inline \
-Wall -Wextra -Werror -c ../../libpulp/tests/libexception.cc \
-o .libs/libexception_la-libexception.o
../libtool: line 1762: g++: command not found

Make configure fails on absent C++ compiler

---

configure.ac

Programs may be using an custom glibc version. This commit add support
for linking libpulp with another glibc provided in the PATH variable
using the `--with-glibc=PATH` switch option.

Add switch option for custom glibc

---

tests/Makefile.am
tests/buildid.c
tests/buildid.py
tests/libbuildid.c
tests/libbuildid_livepatch1.c
tests/libbuildid_livepatch1.in

There was no tests related to the buildid, as stated on #39. This PR adds one by regenerating the target library before the patch is applied with a different code, thereof, with another build id.

Add simple buildid test

---

tests/Makefile.am
tests/missing_function.py
tests/testsuite.py
tools/introspection.c

Previously, the ulp_trigger did not check if the function in the
livepatch container exists before loading the container file and
trying to "replace" the old function.  This commit fixes this by
checking if every function is present in the container file.
Fixes #24  

Check if function exists in container file before applying livepatch

---

lib/ulp.c

When looking for the target library, libpulp first checks if the
complete path to the target library matches the one provided in
the metadata file. This is not a good idea for the following reasons:
1- The build id is enough to identify the target library.
2- The running target library in the target process could be a copy
of the target library provided in the metadata.
3- Many other foldings of case 2-.
Therefore, it is better to rely only on the build id.

Remove check for filename match

---

lib/Makefile.am
lib/interpose.c

Previously, libpulp opened and parsed the ELF content of libdl.so file
to find the address to dlsym to interpose it. Instead of relying on the
.so file, we parsed the alreay loaded ELF program header structures that
is in the program memory to find the address to dlsym.
This commit also removes the requirement of libelf from libpulp.so, but
the tools still require it.

Avoid opening libdl.so to interpose dlsym

---

tools/dump.c

For ulp_apply we need to know just the Build ID, this option saves us having to parse the output in some other language.
Also cleans up a couple of other things, but also happy to clean up further.

Add a build_id only option to ulp_dump

---

Makefile.common
include/ulp_common.h
man/ulp_check.1
man/ulp_packer.1
man/ulp_post.1
man/ulp_trigger.1
tests/terminal.py
tests/testsuite.py
tools/Makefile.am
tools/arguments.h
tools/check.c
tools/check.h
tools/dump.c
tools/dump.h
tools/introspection.c
tools/introspection.h
tools/packer.c
tools/packer.h
tools/patches.c
tools/patches.h
tools/post.c
tools/post.h
tools/ptrace.c
tools/ptrace.h
tools/revert.c
tools/revert.h
tools/trigger.c
tools/trigger.h
tools/ulp.c

This commit unify all ulp tools into one.
Syntax:
```
ulp COMMAND ARG1
```
for instance, old `ulp_trigger` is now `ulp trigger`.

Tool unify

---

include/Makefile.am
include/msg_queue.h
lib/Makefile.am
lib/msg_queue.c
lib/ulp.c
tests/Makefile.am
tests/libpulp_messages.py
tests/testsuite.py
tools/Makefile.am
tools/introspection.c
tools/introspection.h
tools/messages.c
tools/messages.h
tools/ptrace.c
tools/ulp.c

This PR add support to a circular queue system to hold the libpulp messages instead of writing them directly to `stdout`/`stderr`'s target process, and a new tool named `ulp_messages` to retrieve them.

Message queue system

---

lib/Makefile.am
lib/libpulp.versions
lib/ulp_interface.S
tools/introspection.c
tools/introspection.h

Previously, libpulp find symbols address by reading the ELF file of
target process/library and used the offset of the symbol there to
compute its address. Now, look at the remote process of these symbols.
This has the advantage of not having to rely on the process binary
in disk, that could be modified in the meanwhile of loading the
process and applying the patch.
However, this comes with a cost: ptracing the remote process seems
to be slower than reading the in disk information. We reduced this
overhead avoiding looking into libraries which name does not contain
"libpulp". However, there are still margin for optimizations here.

Look for libpulp symbols in remote process

---

tools/ptrace.c

To reduce calls to ptrace, and thus increase performance, we implement
a Translation Lookaside Buffer (TLB) like to store the last ptraced
value in the hope that next reads will be close to the original read
address.

Implement TLB cache in read_bytes

---

configure.ac
include/ulp.h
lib/ulp.c

Since commit 19e37546ebed6d10224b1e73fe74aa93b1949df8, prologues behaved
as:
```
function prologue:
push    %rdi           <-- Unused!
movq    $index, %rdi   <-- Unused!
┌───> jmp     0x0(%rip)
│     <data>  <target function>
│ function entry:
└──── jmp     <function prologue>
```
The first two instructions in the prologue became purposeless, once
they had no semantic behaviour in the program. This commit removes
those two unused instructions in the prologue and reduce its size from
24 bytes to 16 bytes.

Shrink prologue size

---

Makefile.common
tools/arguments.h
tools/dump.c
tools/introspection.c
tools/introspection.h
tools/patches.c
tools/ulp.c

Now, the `patches` command can print the build id of each library
linked agaist the target process using:
```
$ ulp patches -p $(pid) -b
```
Output example:
```
PID: 3092
Global universe: 0
Live patches:
(none)
Loaded libraries:
in /lib64/ld-linux-x86-64.so.2 (3ad62ce668e64d1f7dddd9386f90129c57cc265e):
in /lib64/libdl.so.2 (338aa4d16c98dda7af170cc8e2b59d259bd5d4f4):
in /lib64/libc.so.6 (c3c4f482259e3974d74db18e1cbb52bec0f5094a):
in libparameters.so.0 (8eadb55ed15e43a6c2ae7f6098179bceb3abda2b):
in ../lib/.libs/libpulp.so (6e0710119ae02bd80356c2d5cf02d2f31f4025f7):
in linux-vdso.so.1 (0000000000000000000000000000000000000000):
```
Retrieving the build id of a certain library is straightforward using
grep. For example:
```
$ ulp patches -b -p $(pid) | grep libdl.so | grep -oEi …
```

Print build id of libraries linked against target process

---

tools/ulp_apply

This is a script that we will call from rpm post package install
to update any running processes with the new live patches.
While it could still use things such as better error reporting at
this point it is functional. The name and the final location for
the script are open to change (currently its not installed)

Add ulp_apply tool for packaging

---

tools/dump.c
tools/patches.h

Example: Instead of printing
```
b0 5b fb 1e 66 f8 ac 86 63 38 c7 34 c4 eb 63 e3 20 78 36 ff
```
it now prints
```
b05bfb1e66f8ac866338c734c4eb63e3207836ff
```

Make dump print build id without spaces.

---

include/msg_queue.h
lib/ulp.c
tests/Makefile.am
tests/libparameters_livepatch3.c
tests/libparameters_livepatch3.in
tests/relative_path.py
tools/introspection.c

Now the metadata format accepts relative paths when specifying the path
to the target library. The way it works is by comparing both library
base name and build id to match the library to patch, instead of relying
on the full path to it.
Example:
```
__ABS_BUILDDIR__/.libs/libparameters_livepatch1.so
@.libs/libparameters.so.0
int_params:new_int_params
float_params:new_float_params
```
Notice that the line starting with @ do not require to be the full path
to target library anymore.
Signed-off-by: Giuliano Belinassi <giulianob@gbelinassi.udp.ovpn1.nue.suse.de>

Add support for relative paths in target library

---

.github/workflows/test-suite-sanitizers.yml
configure.ac
tools/Makefile.am
tools/check.c
tools/introspection.c
tools/introspection.h
tools/messages.c
tools/packer.c
tools/revert.c
tools/trigger.c

This PR enables and fixes all address sanitizer problems in ulp tools.
Address sanitizer can be enabled with `--enable-address-sanitizer` in configure.

Enable support for address sanitizer in ulp tools

---

include/ulp.h
lib/libpulp.versions
lib/ulp.c
lib/ulp_interface.S
tests/Makefile.am
tests/revert_all.py
tests/revert_and_patch.py
tests/testsuite.py
tools/introspection.c
tools/introspection.h
tools/trigger.c
tools/ulp.c

A new option is available for trigger: `--revert-all`. Usage:
```
$ ulp trigger -p $pid --revert-all $libname $metadata
```
`--revert-all` causes trigger to revert all patches applied to `$libname` in
the target process with pid `$pid`.
In case `--revert-all` is provided,  `$metadata is optional`. In case the
metadata is provided with patch content, the new patch will be atomically
applied to the process after all older patches have been reverted, so
the target process doesn't get a chance to run the unpatched version of
the function. If `$metadata` is not provided, no patch will be applied
after removal.
Co-authored-by: Simon Lees <sflees@suse.de>

Add `--revert-all` for trigger

---

tests/deadlock.py

deadlock.py tests had a chance to fail because it finished all attempts
of livepatching before timing out. Previous value did work because the
ptrace functions were slow, but now they are optimized and livepatching
can be very fast.

Bump deadlock attempts to 10000

---

include/interpose.h
include/ulp.h
include/ulp_common.h
lib/interpose.c
lib/ulp.c
tests/access.c
tools/introspection.c

Target libraries are already opened by target process, so there is no
point in opening them again.
This also fix a patching issue if the target .so file is not found, but
it was already loaded by the process.

Avoid opening target library for patching

---

tests/testsuite.py

Printing the livepatch's metadata content in the CI help debugging
issues on the CI.

Print metadata content on logs

---

tests/testsuite.py

Also prints the .dsc file, as it is useful for debugging CI issues as
well.

Print description file on test logs

---

include/Makefile.am
include/error.h
lib/Makefile.am
lib/error.c
lib/interpose.c
lib/ulp.c

If a fatal error was found when livepatching, we disable the
livepatching mechanism instead of exiting the target process.
The only case when we crash the target process is if libpulp
initialization fails. It may be better to warn the user that the
livepatching capabilities is not working on process startup rather than
silently disabling it and then some sysadmin finds out that something
went wrong weeks later.
Closes #48 

Block livepatching if fatal error is found

---

tests/Makefile.am

There is a race condition in the testsuite. Serialize tests for now.

Serialize testsuite

---

tests/Makefile.am
tests/libmanyprocesses.c
tests/libmanyprocesses_livepatch1.c
tests/libmanyprocesses_livepatch1.in
tests/manyprocesses.c
tests/manyprocesses.py
tools/trigger.c

Previously, trigger only supported directories when applying multiple
patches. This commit add support wildcards instead, which is more
versatile.
This also fixes a race condition on manyprocesses.py test.

Add support for wildcards in trigger

---

.github/workflows/test-suite-valgrind.yml
configure.ac
tests/Makefile.am
tests/terminal.py
tests/testsuite.py

Enable valgrind support on testsuite to catch memory errors in libpulp.so. This complements the current libsanitizer tests.
Closes #60

Valgrind support

---

README.md
include/ulp_common.h
lib/interpose.c
lib/ulp.c
tests/Makefile.am
tests/libtls.c
tests/libtls_livepatch1.c
tests/libtls_livepatch1.in
tests/offsets.py
tests/tls.c
tests/tls.py
tools/packer.c

TLS variables (declared with __thread keyword) are global variables
private to each thread.  They are implemented by allocating a new
variable every time a thread is spawn.
To reference an TLS variable on a livepatch, one can use the following
notation:
where `banner` is the original TLS variable we want to reference, and `ti`
is a variable that will holds the TLS offset metadata required to access
banner. Note that ti is not a pointer or reference, but a instance of
`tls_index`.
To reference the original TLS variable, one can write:
```
void *__tls_get_addr(tls_index *);
void *reference_to_banner = __tls_get_addr(&ti);
```
and then `reference_to_banner` will contain a pointer to the original var
in current thread.

Add support for TLS variables

---

common/common.c
include/interpose.h
include/ulp_common.h
lib/interpose.c
lib/ulp.c
tests/Makefile.am
tests/dozens.c
tests/libprocess_livepatch1.in
tests/process.c
tests/process.py
tests/process_revert.py
tests/testsuite.py
tools/introspection.c
tools/packer.c
tools/packer.h

Previously, libpulp only supported livepatching functions that were
available to the program through libraries.  We now expand this support
to functions that isn't provided by libraries (e.g., main).
This also adds support to patching symbols not present in .dynsym
section by looking the symbol address on .symtab during packer time.
Since we must ensure that buildid matches, we only patch if the target
process is the same during packer time.

Add initial support for livepatching functions in process

---

tests/Makefile.am

Mistakenly introduced in ea4cf9845ce3326dc0f5ca89e60bbcaf0079be50.

Fix process_DEPENDENCIES duplicate

---

common/common.c

On GCC 12, fgets return value must be catch when -Werror is specified.

Get libpulp to compile on GCC 12

---

tests/manyprocesses.py
tools/introspection.c
tools/trigger.c

1. Remove some debugging informations that were leftover from the CI
heisenbug.
2. Show which process failed when patching multiple processes.
3. Fix a small bug which made trigger crash after patching multiple
processes.

Add better messages

---

tests/manyprocesses.py
tools/introspection.c
tools/trigger.c

If `revert-all=LIB` were passed to trigger without the -p parameter
and without a wildcard, then the `ulp` tool crashed with a SEGFAULT.
Add support to this case.

trigger: Fix `revert-all=LIB` without -p

---

tools/trigger.c

Accepting .rev files should be allowed when batch processing. Update
trigger accordingly.

Accept `.rev` in batch processing

---

common/common.c
include/ulp.h
include/ulp_common.h
lib/ulp.c
tools/arguments.h
tools/check.c
tools/introspection.c
tools/introspection.h
tools/messages.c
tools/patches.c
tools/patches.h
tools/trigger.c
tools/ulp.c

Instead of showing which libraries are loaded in the program,
now only show which libraries are livepatchable in the program, and
show which livepatches are loaded to that library. This should improve
readbility when querying for livepatches.
Example:
```
in ./libssl.so.1.1:
livepatch: libcve-2021-3449_livepatch1.so
```

Update patches to show more meaningful information

---

tools/patches.c

If the `ulp` tool is loaded with libpulp.so, livepaches capabilities are
loaded with it and the process turns to be livepatchable. However,
ptrace cannot be used to attach to itself, so the livepatching mechanism
does not work. So avoid failure by simply not adding itself to the
process list.

Fix self-querrying

---

tests/Makefile.am
tests/livepatchable.py
tests/testsuite.py
tools/Makefile.am
tools/arguments.h
tools/livepatchable.c
tools/livepatchable.h
tools/post.c
tools/ulp.c

The new command:
```
$ ulp livepatchable <library>
```
can be used to check if a certain library is livepatchable.

Add `livepatchable` command to check if a library is livepatchable

---

lib/ulp.c
tests/Makefile.am
tests/access2.c
tests/access2.py
tests/libaccess_livepatch2.c
tests/libaccess_livepatch2.in
tests/offsets.py
tools/introspection.c
tools/packer.c
tools/packer.h

Before this patch, the user could only specify
```
#target_symbol:target_symbol_ref:addr1:addr2
```
however, those address can change when you modify the livepatch
sourcecode. Therefore, we now support:
```
#target_symbol:target_symbol_ref
```
and now `addr1` and `addr2` will be collected analysing the target
library and livepatch container automatically on packer time.

Find address of reference to symbol by its name

---

common/common.c

osc requires that return values of functions be used. So check for
errors in getrandom.

Fix compilation in GCC 12

---

tests/Makefile.am
tests/revert_with_invalid.py
tests/testsuite.py
tools/introspection.c
tools/trigger.c

Previously, if the metadata is invalid and --revert-all were passed,
all patches associated with library would be reverted. This behaviour
is not desired, once it would expose the target application to serious
bugs fixed in the previous patch. Block revert-all in this case.

Avoid reverting all patches if metadata is invalid

---

include/Makefile.am
include/terminal_colors.h
tests/libparameters_livepatch2.in
tools/packer.c
tools/packer.h

Previously, the .dsc parser did not provide useful error messages for
the user if an error occured when parsing it. Now, we implement an
mechanism to print errors in the file that resembles GCC 5.0+. This
should improve diagnostics.
Closes #118 

Add better error messages on .dsc parser

---

common/common.c
include/error_common.h
include/terminal_colors.h
include/ulp_common.h
lib/ulp.c
tools/elf-extra.c
tools/introspection.c
tools/introspection.h
tools/packer.c
tools/packer.h
tools/patches.c
tools/trigger.c
tools/ulp.c

Trigger messages can be quite complicated to understand because of the
huge amount of information displayed on screen.
We now refactor this to provide more simplified messages:
For instance, when triggering all processes with the patches in current
directory:
```
$ ulp trigger '*.so'
Summary:
ulp-test (pid: 25606):
SKIPPED ./cve-2022-0778_livepatch1-1.1.1l-150400.2.47.so: Build ID mismatch
SKIPPED ./cve-2022-0778_livepatch1-1.1.1l-150400.3.4.so: Build ID mismatch
SKIPPED ./cve-2022-0778_livepatch1-1.1.1l-150400.3.11.so: Build ID mismatch
SKIPPED ./cve-2022-0778_livepatch1-1.1.1l-150400.3.3.so: Build ID mismatch
SKIPPED ./cve-2022-0778_livepatch1-1.1.1l-150400.3.15.so: Build ID mismatch
```
Or when asking to revert all patches to libcrypto.so to all processes:
```
ulp trigger …
```

Improve trigger messages

---

configure.ac
include/error_common.h
include/ulp_common.h
lib/ulp.c
tests/Makefile.am
tests/endbr64.c
tests/endbr64.py
tests/libendbr64.c
tests/libendbr64_livepatch1.in
tools/post.c

Add support to functions starting with endbr64 instruction
Some functions can begin with `endbr64` in order to validate indirect
jumps in x86_64, even if -fpatchable-functions-entry is enabled on
compilation time.
For instance, on Tumbleweed's glibc, it can have:
__aio_read:
endbr64
nop
nop
...
As you can see, the endbr64 insn is placed before the nop opcodes.
Previosly, trying to patch this function would result in bad insn,
as it expected the two nop's to be the two first insn of __aio_read.
This patch makes libpulp check if endbr64 is present there and write
the redirect after it.
It also closes #126

Endbr64 support

---

tests/librecursion_livepatch1.c
tests/librecursion_livepatch1.in
tools/introspection.c

Tumbleweed's gcc found an use-after-free bug, which is now fixed.
Also update the recursion.c testcase for it to build with the
current glibc version.

Get libpulp to build on Tumbleweed.

---

include/Makefile.am
include/ld_rtld.h
lib/interpose.c
lib/libpulp.versions
tests/Makefile.am
tests/dlsym.c
tests/dlsym_lock.py

Glibc's dlsym behaviour changes depending of where it is being called.
Proof of this can be found in glibc's dlfcn/dlsym.c. Notice that
RETURN_ADDRESS(0) is passed to internal functions, which gets the
previous frame address.
The practical behaviour is that if we interpose dlsym, then software
that interposes functions from glibc will find libpulp functions
instead, and libpulp will find the software interposed functions,
creating an infinite recursion.
Therefore, we can not interpose dlsym and use a custom lock, as we do
for the other functions, and we instead check if the dlsym lock is
held.

Do not interpose dlsym

---

.github/workflows/test-suite.yml
common/common.c
lib/interpose.c
tests/Makefile.am
tests/libstress.c
tests/libstress_livepatch1.c
tests/libstress_livepatch1.in
tests/manyprocesses.py
tests/stress.c
tests/stress.py
tests/testsuite.py
tools/introspection.c
tools/introspection.h
tools/patches.c
tools/post.c
tools/trigger.c
tools/ulp.c

Fix case where target process name is not found
In some cases, /proc/pid/comm is not available to be parsed. If this
happens, return (null) string to show that.
Also avoid reparsing this file when possible.

 Fix case where target process name is not found

---

tests/libstress_livepatch1.c
tests/stress.c
tests/stress.py

The `stress` test previously used pyexpect stdout redirection mechanism
that used an unreasonable amount of RAM (>16Gb). Refactor this test so
that it uses a single process on the .py script and everything else is
handled in `stress.c`.

Refactor `stress` test

---

common/common.c
configure.ac
include/ulp_common.h
lib/interpose.c
lib/libpulp.versions
tests/Makefile.am
tests/pcqueue.c
tests/pcqueue.py
tests/stress.c
tests/stress.py
tools/Makefile.am
tools/arguments.h
tools/introspection.c
tools/introspection.h
tools/messages.c
tools/patches.c
tools/patches.h
tools/pcqueue.c
tools/pcqueue.h
tools/ptrace.c
tools/ptrace.h
tools/trigger.c
tools/ulp.c

This PR refactors code in tools side so that livepatching is faster on a large number of processes.
Such changes include:
- Replace sprintf with strcpy to concatenate strings.
- Limit the number of symbols to check if a library is livepatchable.
- Reduce the amount of target processes reads.
- Add an optional cache to speedup symbol discovery.
- Replace ptrace with process_vm_writev/readv when possible.
- Reduce the number of attach/detach.
- Avoid wildcard matching if input is not a wildcard.
- Discover libpulp symbols in a separate thread.
- Add support to thread sanitizer.
That changes reduces the trigger time on `stress` test (4000 processes) from 26.8s to 4.3s on an Intel Xeon E5 2670-v3.

Drastically improve patching time.

---

configure.ac
man/ulp.1
tests/Makefile.am
tests/libprefix.c
tests/libprefix_livepatch1.in
tests/prefix.c
tests/prefix.py
tests/testsuite.py
tools/check.c
tools/dump.c
tools/introspection.c
tools/introspection.h
tools/trigger.c
tools/ulp.c

When `ulp` tool runs in a chroot'ed directory, the `realpath` function will return the path to the root from the chroot, not the path from the true root.  This commit introduces the --root=PREFIX options which appends PREFIX to the path to the patch file right before sending it to the target process, providing a way to workaround this chroot problem.

Add -R --root=PREFIX option

---

scripts/extract_function.sh
scripts/glibc.sh
scripts/setup_package.sh

Previous download scripts used obscure OSC api in order to get the packages. In this version we refactor those scripts to parse public .html information in order to get what we need, without relying on an API of some sort. This should improve maintainability of code.

Refactor download package scripts

---

tools/extract.c

ELF magic number should be 127 ELF, and not have those extra numbers.
Fixes #155 

Fix ELF magic number comparison

---

common/Makefile.am
tools/introspection.c

Previously, libpulp.so.0 were being linked against libunwind, but no function of this library is called inside libpulp. This library also do not have any constructors. Hence, only the tools need to link against this library.
Also fix a file descriptor leak in the stack check code. Since it is not used in the package updater, this is not critical.

Fix linkage of libunwind and file descriptor leak

---

include/ulp.h
include/ulp_common.h
lib/interpose.c
lib/ulp.c
tools/extract.c

This commit add comments to function and structures in an attempt to
explain what they do more clearly.  This also flags stuff that has been
deprecated and neeeds further revision.
This also removes the old dlinfo cache which was never used, thus this code is not needed anymore.

Refactor and document functions/structues

---

scripts/collect.sh
tools/patches.c

libcrypto.so.1.1 required to read around 200 symbols in order for `patch` to detect it as a livepatchable library.  Hence we bump the number of symbols to read from 64 to 8000.  This value of 8000 is found by analyzing all libraries found in /usr/lib64 and its subfolders for how many symbols it would need to be read in order to decide if the library is livepatchable.
Workarround #159

Fix `patches` not detecting libcrypto as livepatchable

---

include/error_common.h
tests/Makefile.am
tests/nolibpulp.py
tools/introspection.c

If trigger was called with -p PID, where PID is a process without libpulp loaded, then trigger crashed.  This commit fixes this problem by moving the necessary check accordingly.

Fix case where trigger is called with pid of non-livepatchable process

---

common/common.c
include/error.h
include/error_common.h
include/ulp_common.h
lib/error.c
lib/interpose.c
lib/libpulp.versions
lib/ulp.c
lib/ulp_interface.S
man/ulp.1
tests/Makefile.am
tests/group_disable.py
tests/path_disable.py
tests/set_patchable.py
tests/testsuite.py
tests/user_disable.py
tools/Makefile.am
tools/arguments.h
tools/extract.h
tools/introspection.c
tools/introspection.h
tools/patches.c
tools/patches.h
tools/set_patchable.c
tools/set_patchable.h
tools/trigger.c
tools/ulp.c

This PR adds the ability for libpulp to disable livepatching given some parameters.
The first parameter is through the environment variables:
1. `LIBPULP_DISABLE_ON_PATH=path_wildcard1:path_wildcard2:...`
2. `LIBPULP_DISABLE_ON_USERS=user_wildcard1:user_wildcard2:...`
3. `LIBPULP_DISABLE_ON_GROUPS=group1_wildcard:group2_wildcard:...`
Each variable accepts multiple arguments separated by `:` token. For example, if the variable:
`LIBPULP_DISABLE_ON_PATH=*/numserv:/home/*`
is defined, then all processes with name `numserv` and all processes which binary is housed in /home/* will have livepatching blocked regardless if run with libpulp or not.
Another example:
`LIBPULP_DISABLE_ON_USERS=:1000:giulianob`
will block livepatching on users with uid = 1000 or which name is `giulianob`. 
Now, since …

Add mechanism to opt-out livepatching

---

tools/trigger.c

Instead of showing that livepatching failed when it was already applied, show that it was skipped so the user won't think this is an error.

Show `SKIPPED` instead of `FAILED` when patch is already applied

---

tools/ptrace.c

On ptrace.c there is a typo which cause the code to fallback to use ptrace instead of writev. This commit fixes this.

Fix typo in ptrace.c

---

.github/workflows/test-suite.yml
configure.ac
include/error_common.h
include/ulp.h
include/ulp_common.h
lib/interpose.c
lib/ulp.c
tests/Makefile.am
tests/block_mprotect.c
tests/blocked.py
tests/mprotect.py
tests/mprotect_patch.py

Processes launched by systemd can specify:
MemoryDenyWriteExecute=yes
to block redefining page flags with EXEC flag. This is a problem for livepatching, once we need to redefine the page flags in order to install the redirection jump.
This commit adds a mechanism to detect this case and disable livepatch accordingly, as we don't have the necessary engine features yet to circunvent this problem from `ulp` side.

Detect if mprotect is blocked when libpulp is initalized

---

tools/patches.c

While finding out which libraries are livepatchable, it may be not possible to read the area because of permission errors. In that case, send this error to the debug output instead of stderr, which then would require -v (verbose) switch.
Closes #174

Do not warn about being unable to read symbol preamble

---

man/ulp.1
tests/manyprocesses.py
tests/testsuite.py
tools/arguments.h
tools/trigger.c
tools/ulp.c

Previously, the output of `ulp trigger` counted the number of prcoesses that were patched skipped and failed, but this counting did break at times because it only remembered the last output of trigger_one_process. Now it logs into a bitfield to log if there was a success skip or failure.
Fixes #177

Fix livepatch status counting

---

man/ulp.1

Two trigger commands were undocumented. Do it in this commit.
Fixes #179

Document --recursive and --timeout

---

include/error_common.h
lib/ulp.c
tests/revert_all.py
tools/introspection.c
tools/trigger.c

When reverting all patches with --revert-all of a library that do not have liveatches installed, the `ulp` tool warned the user about this but that is designed behaviour on the first livepatch installation. This commit fixes this.
Closes #180

Fix warnings when reverting all patches from a library

---

tests/Makefile.am
tests/patches.py
tools/patches.c

Previously, the ulp tool crashed when -p is given a pid which do not exist. This commit fixes this.
Closes #186

Fix `ulp patches -p PID` crashing when PID do not exist

---

tools/patches.c

Trigger printed "error gathering target process information". Print this on patches as well instead of "failed to parse data for live-patchable process".

Standardize process read failure due to bad PID

---

tests/buildid.py
tests/nolibpulp.py
tests/testsuite.py
tools/patches.c
tools/trigger.c

Previously, trigger with -p PID runs with batcn processing mode disabled. This may not be desired, as someone could want to install multiple patches into a single process.
Closes #187

Enable batch processing with -p PID

---

tests/Makefile.am
tests/chroot.c
tests/chroot.py
tools/introspection.c
tools/introspection.h
tools/trigger.c

Some processes in SLE chroots into /proc. This patch add support for those processes by detecting such cases and escaping the chroot through the root directory of the process with pid = 1.

Add support for process chrooted into /proc

---

include/error.h
include/insn_queue.h
tools/extract.c
tools/introspection.c
tools/packer.c

Previously, a sanity check in the `ulp` tool checking if the symbols declared in the description section is actually in the code section. This check was done by loading the patch with dlopen. However some security flags in openbuildservice introduces a different behaviour on dlopen, turning it unreliable to check this.
Now we parse the file as a ELF and check if the symbol is in the symbol table.

Replace dlsym with ELF file parsing for checking for symbol existence

---

examples/README.md
examples/cplusplus/1-class/Makefile
examples/cplusplus/1-class/README.md
examples/cplusplus/1-class/a_livepatch1.cpp
examples/cplusplus/1-class/a_livepatch1.dsc
examples/cplusplus/1-class/class.cpp
examples/cplusplus/2-private_class/Makefile
examples/cplusplus/2-private_class/README.md
examples/cplusplus/2-private_class/a_livepatch1.cpp
examples/cplusplus/2-private_class/a_livepatch1.dsc
examples/cplusplus/2-private_class/class.cpp
examples/cplusplus/3-indirect_call/Makefile
examples/cplusplus/3-indirect_call/README.md
examples/cplusplus/3-indirect_call/a_livepatch1.cpp
examples/cplusplus/3-indirect_call/a_livepatch1.dsc
examples/cplusplus/3-indirect_call/class.cpp
examples/cplusplus/4-global_var/Makefile
examples/cplusplus/4-global_var/README.md
examples/cplusplus/4-global_var/a_livepatch1.cpp
examples/cplusplus/4-global_var/a_livepatch1.dsc
examples/cplusplus/4-global_var/test.cpp
examples/cplusplus/5-queue/Makefile
examples/cplusplus/5-queue/README.md
examples/cplusplus/5-queue/a_livepatch1.cpp
examples/cplusplus/5-queue/a_livepatch1.dsc
examples/cplusplus/5-queue/class.cpp

Libpulp provides livepatching capabilities that is general enough to support many programming languages, not only C.  However, writing livepatches in a language that allows more abstractions may not be as straightfoward as in C.
To illustrate this we now provide the following examples in C++:
1-class: Show how C++ methods can be livepatched.
2-private_class: Show how private C++ functions can be livepatched. 3-indirect_call: Show how non-inlined private functions can be called
from a livepatch to avoid code growth
4-global_var: Show how a private global variable can be accessed from a
livepatch
5-queue: Show how template methods can be livepatched.

Add live patching examples in C++

---

.github/workflows/test-suite.yml
examples/cplusplus/1-class/Makefile
examples/cplusplus/2-private_class/Makefile
examples/cplusplus/3-indirect_call/Makefile
examples/cplusplus/4-global_var/Makefile
examples/cplusplus/5-queue/Makefile

'configure' set default target installation directory is '/usr/local/bin/ulp', at the same time, ulp could be installed to '/usr/bin/', thus, we should find ulp in examples/*/Makefile, it's better way.

Use which to find ulp files when compiling examples

---

tools/patches.c
tools/ptrace.c
tools/ptrace.h
tools/ulp.c

YAMA has a security feature that block ptrace of non-child processes. Check for that when the command is issued to make sure everything will work as it should.

Check for ptrace_scope before doing ulp operations

---

tests/process_access.c

clang-18 inserts new *.specialized.* symbols in banner_get and then calls it instead of the original banner_set function.  This is undesired once we livepatch banner_set so disable optimizations in this function.

Avoid *.specialized.* symbols in process_access test.

---

tests/asunsafe_conversion.py
tools/extract.c
tools/packer.c

This message may happen if library does not contain either .dynsym or .symtab sections, which may happen and is fine. So do not issue an error because of that.

Remove "Unable to get section data." message

---

scripts/setup_package.sh
tools/arguments.h
tools/extract.c
tools/ulp.c

SUSE packages now strip the .symtab away and store it in the debuginfo, so get the debuginfo for the analysis as well.
ulp extract now accepts `-d` to specify a debuginfo.

Use debuginfo when extracting information about the packages

---

.gitignore
include/error_common.h
lib/ulp.c
tests/Makefile.am
tests/libvisibility.c
tests/libvisibility_livepatch1.c
tests/libvisibility_livepatch1.in
tests/libvisibility_livepatch2.c
tests/libvisibility_livepatch2.in
tests/visibility.c
tests/visibility.py
tools/packer.c

Previously, libpulp used RTLD_LAZY in dlopen, which resulted in livepatch that should have failed to apply being applied. In SLE-15-SP4, those patches seems to work regardless of that, but in SP5 it result in problems. Hence, change this policy to RTLD_NOW to force all symbols to be loaded by the linker at patch load time.
Also, this commit now encode the symbol references on packer even if not specified in .dsc by capturing it from the .json dumps, which should improve the support for strong externalizations.

Change .so load policy and fix symbol visibility problems

---

include/insn_queue_lib.h
lib/Makefile.am
lib/insn_queue.c
lib/ulp.c
tests/Makefile.am
tests/insn_queue.c
tests/insn_queue.py
tools/insn_queue.c
tools/trigger.c

Relying on `/proc/self/mem` to bypass `mprotect` issues turn out to be unreliable: the process can change into another user which does not have access to this file, hence ptrace as `ulp` being root is the only way out.
This reverts commit 795c59019edafb0135560e4a8c9630164b4ef784.

Revert "Remove insn_queue from libpulp"

---

tools/introspection.c

SLE Micro contains some quirks with the transactional filesystem. Take them into account, like:
- /proc/self/mem may not be accessible and livepatching should be disabled in those cases.
- realpath returns NULL on paths that are accessible, thus attempt to continue in those cases.

Fixes for SLE Micro

---

common/Makefile.am
common/insn_queue.c
configure.ac
include/Makefile.am
include/insn_queue.h
include/insn_queue_lib.h
include/minielf.h
include/ulp_common.h
lib/Makefile.am
lib/gdb_interface.c
lib/insn_queue.c
lib/libpulp.versions
lib/minielf.c
tests/insn_queue.c
tools/insn_queue.c
tools/introspection.c

Libpulp requires the `ulp` tool in order to load and apply livepatches, using the `ptrace` mechanism for that.  This introduces a series of issues while debugging the application, such as unable to livepatch an application lauched under gdb, and unable to livepatch programs being analyzed under valgrind's memcheck.
This PR introduces a gdb interface to it.  To build it, configure libpulp with:
```
configure --enable-gdb-interface
```
and livepatches can be applied by called the functions:
- `gdb_ulp_apply("<path-to-livepatch>")`
- `gdb_ulp_revert("<path-to-livepatch>")`
Such functions can also be called from the program itself by calling `dlsym(NULL, "gdb_ulp_apply")` to get the pointer to the function and then calling it.

Introduce GDB interface

---

common/common.c
lib/arch/x86_64/patch.c

There is no need to insert two WRITEs for each function, as we can craft the final prologue before inserting it.

Remove one WRITE insn for each function

---

configure.ac
lib/ulp.c

Fix build id mismatch problems with glibc 2.40
Libpulp showed a weird behavior when loaded with glibc 2.40: some tests
failed with a buildid mismatch.  The source of the issue is the faulty
buildid computation algorithm.  Replace it by another one written by
Richard Biener in:
https://gcc.gnu.org/legacy-ml/gcc/2019-02/msg00120.html

Fix buildid glibc 2.40

---

configure.ac
include/arch/powerpc64le/arch_common.h
lib/Makefile.am
lib/arch/powerpc64le/patch.c
lib/arch/powerpc64le/ulp_prologue.S
tests/chroot.c
tests/chroot.py
tests/libmanyprocesses.c
tests/libmanyprocesses_livepatch1.c
tests/libparameters.c
tests/libparameters.h
tests/libparameters_livepatch1.c
tests/libparameters_livepatch3.c
tests/libprocess_livepatch1.c
tests/libpulp_messages.py
tests/manyprocesses.c
tests/manyprocesses.py
tests/mprotect_patch.py
tests/nolibpulp.py
tests/parameters.c
tests/parameters.py
tests/process.c
tests/process.py
tests/process_revert.py
tests/relative_path.py
tests/syscall_restart.c

This commit fixes a bug in libpulp where functions with more than 8
parameters could not be livepatched due to a stack corruption.  This
fix is done by introducing a new prologue in ppc64le, together with
an ulp stack to save data (TOC and LR registers) while redirecting
the function.
Closes #217

Fix livepatching on ppc64le when functions have more than 8 parameters

---

man/ulp.1

Relevant groff warning:
groff-message troff:<standard input>:529:
warning: macro 'TPut' not defined (possibly missing space after 'TP')
[usr/share/man/man1/ulp.1.gz:1]

Fix typo in manpage

---

tools/ulp.c

The suggested command-line doesn't work if the user is not logged as root.  Hence provide another that works even if logged as an ordinary user with sudo privileges.

Improve error message when ptrace_scope is enabled

---

lib/arch/powerpc64le/ulp_prologue.S

Reg5 and Reg6 are used as temp regs and their original values are already backed up. Skip pushing temp data as values are constructed before every use.

Skip saving temp registers redundantly on ulp_stack resize

---

tests/notes.ld

The linker script used in the notes test case is a simplified version of default linker scripts in the rolling release versions of debian (sid) and opensuse (tumbleweed). The linker script has been tested to work with these distros, but not with others, such as SLE 15 (SP4). Other distros have different linker scripts that fulfill requirements of their toolchains, such as the presence of special symbols.
In the case of SLE 15 SP4, the following symbols are automatically defined by their default linker script:
__init_array_start
__init_array_end
however, our manually crafted linker script does not create them, and the compilation of the test case fails with the following error:
libtool: link: gcc -fpatchable-function-entry=16,14 -Wall -Wextra -Werror
-o notes notes-notes.o -g -O2 …

Improve linker script used by the notes test case

---

lib/arch/powerpc64le/ulp_prologue.S
tests/Makefile.am
tests/librecursion2.c
tests/librecursion2.h
tests/librecursion2_livepatch1.c
tests/librecursion2_livepatch1.in
tests/recursion2.c
tests/recursion2.py

Correcting pointer access to top of stack
The current implementation always retrieves the deepest LR and TOC (belonging to very first patch) from the stack. Since, r5 contains base of stack and "decremented USED_SIZE" is not added to point to top of stack, so r5 keep pointing to bottom when retrieving LR/TOC values for any patched function.
Authored-by: [dubeyabhishek](https://github.com/dubeyabhishek)

 Correcting pointer access to top of stack on restoring LR/TOC

---

tests/notes.py

For some reason, the build id in ppc64le of the main process 'notes' is not loaded correctly by libpulp, either because it doesn't exist (missing in the linker script) or a deeper issue in libpulp.
Skip it for now. We don't need it.

Skip 'notes' test in ppc64le

---

include/arch/powerpc64le/arch_common.h
include/arch/x86_64/arch_common.h
tests/notes.py
tools/introspection.c
tools/introspection.h
tools/patches.c

The powerpc64le port exposed a bug in `parse_dynobj_elf_headers` that made it compute wrong addresses of objects that were not loaded shared objects (like the main executable for instance).  This commit fixes this problem, hence making the `notes` test work on powerpc64le.
This also eliminates the necessity of having a hardcodede EXECUTABLE_START constant, as custom linkscript binaries may change this value after all.
Closes #235

Fix dynobj parsing from the `ulp` tool side

---

lib/arch/powerpc64le/patch.c
lib/arch/powerpc64le/ulp_prologue.S
tests/Makefile.am
tests/testsuite.py
tests/textrel.py

Previous versions of libpulp for the ppc64le generated text relocations, which makes the dynamic linker resolve them when the library is being loaded.  This actually causes a problem when the program is loaded with seccomp mprotect protection, because it needs to set the page to EXECUTABLE and WRITABLE for a short period of time, causing the application to crash.
This commit fixes this by refatoring the code into not using TEXTREL. This comes with a performance cost because __tls_get_addr needs to be called in order for this to work, and more registers needs to be saved for this function to be successfully called.

ppc64le: rewrite ASM code to not generate TEXTREL

---

lib/arch/powerpc64le/patch.c

This patch addresses the mmap livepatching issue[1] by allocating ulp_stack through the brk() syscall.
Rather than using the brk() system call interface
provided by glibc, brk is invoked directly via glibc's syscall() function. This change shifts the existing limitation from mmap() to glibc's syscall().
However, glibc's brk() function remains available
for future patching.
Benefits of the New Approach:
1)The simplicity of the syscall() interface reduces
the vulnerability surface compared to mmap().
Hence, non-patchable exception for syscall is better.
2)It eliminates the need to copy the content of the
old ulp_stack after resizing.
[1] https://github.com/SUSE/libpulp/issues/239

Memory allocation for ulp_stack using brk syscall

---

configure.ac

gcc-15 ppc64le needs this flag for libpulp to compile.  Check if the compiler supports it and pass the flag accordingly.

Improve -msplit-patch-nops detection

---

include/error.h
include/error_common.h
lib/error.c
lib/interpose.c
tests/Makefile.am
tests/run_libc.py

Previously, if libpulp is loaded in the entire system, calling
$ /lib64/libc.so.6
results in an 'assertion error' rather than it displaying the glibc version installed in the system.  This commit fixes this using the following approach:
1- If libdl symbols are not found, we disable livepatching in the process.  This is either due to:
a. libdl is the main process itself, resulting dlopen(RTLD_NEXT)
to fail.  In this case the library was just called for displaying
the version number, and it is safe to disable livepatching.
b. libdl was not loaded in the system.  In this case the application
can't run dlopen/dlsym, thus we can't livepatch the process.
2- If libdl is not loaded but libc *is* loaded (which can happen on
older versions of glibc), then pass ahead the calls to the alternate …

Fix calling libc.so.6 triggering an assertion error

---

lib/interpose.c
tests/Makefile.am
tests/glibc_private.py

Some symbols from glibc are not meant to be called by external programs, those have `GLIBC_PRIVATE` appended to them, and no other public symbol available to link against.
One of such symbols is `__libc_reallocarray`.  But we don't need to interpose it, as it will eventually call realloc which is a function we interpose.  So eventually the lock will be held correctly.

Make sure libpulp.so is built without GLIBC_PRIVATE symbols

---

lib/arch/powerpc64le/patch.c
lib/arch/powerpc64le/ulp_prologue.S

Previously, the ppc64le prologue are vulnerable to a race condition when assemblying the new function address to redirect.
If the function is patched, the code sequence:
```
lis   %r5,      0x1122
ori   %r5, %r5, 0x3344
lis   %r6,      0x5566
ori   %r6, %r6, 0x7788
```
can be replaced by a second patch, which means r5 and r6 could have a partial address already assembled, thus resulting in a jump to unknown location, causing the program to crash.
This commit fixes this by storing this address in the prologue as if it were code, in the `ulp_prologue_new_function_addr` variable.
Closes #249.

Fix race condition in ppc64le patching

---

tools/extract.c
tools/packer.c

Users have attempted to use linker scripts instead of valid ELF files or JSON metadata dumps as input for `packer` tricked by the .so extension in SUSE Linux.  Hence we should display a better error message in such cases.

Improve error messaage when container isn't a valid JSON

---

tests/run_libc.py

On x86_64 openSUSE Tumbleweed, libc.so.6 is found under /usr/lib64; whereas on Debian, it is found under an architecture-dependent path, such as /usr/lib/x86_64-linux-gnu/libc.so.6, which fails the lookup in tests/run_libc.py.
This patch changes the search logic to use GCC's -print-file-name option, and converts it to an absolute path with realpath.
On Tumbleweed:
$ gcc -print-file-name=libc.so.6
/usr/lib64/gcc/x86_64-suse-linux/15/../../../../lib64/libc.so.6
$ realpath `gcc -print-file-name=libc.so.6
/usr/lib64/libc.so.6
On Debian:
$ gcc -print-file-name=libc.so.6
/usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu/libc.so.6
$ realpath `gcc -print-file-name=libc.so.6`
/usr/lib/x86_64-linux-gnu/libc.so.6

Use gcc to find libc and libdl

---

tools/introspection.c
tools/trigger.c

The `ulp trigger` command uses two threads, one to discover which processes are suitable to patching, and another to actually patch the process.  This is done for performance issues, as discovery is much faster than patching and can be done in parallel.
But what happens if the process is terminated right after the process discovery, but before patching?  Trigger will try to hijack the threads but it will fail with a ENOENT.  This is not a valid failure and should be marked as "SKIPPED".  This commit fixes this by capturing this ENOENT error and mark as such.
Fixes #254.

Do not attempt to hijack terminated processes

---

lib/interpose.c
tests/Makefile.am
tests/dlopen.c
tests/dlopen.py

Since `dlopen` and `dlmopen` were interposed, it changed the search paths because the caller were now `libpulp.so.0` rather than the original application.  This interposition were done for reasons of ensuring that we knew when an application has called `dlopen` by locking a lock in libpulp, but its not necessary anymore since we hijack the `dl_load_lock` from glibc.

Fix dlopen directory lookup behavior
