configure.ac

Check for autoconf-archive availability

---

.github/workflows/test-suite.yml
README.md

Add CI (take 3)

---

tools/packer.c
tools/packer.h
tools/post.c

See individual commit messages for the rationale.

Let libc.so be live-patchable

---

tests/Makefile.am
tests/cancel.c
tests/cancel.py

See the commit message for an explanation.

Thread cancellation problem

---

tests/deadlock.py

Fix missing import of subprocess in deadlock test case.

Fix deadlock test case failure

---

.github/workflows/test-suite-clang.yml
.github/workflows/test-suite.yml
configure.ac
man/ulp_trigger.1
tools/Makefile.am
tools/introspection.c
tools/introspection.h
tools/trigger.c

Check the stack before applying a live patch

---

tools/ptrace.c

Previously, `trigger` waited for 1000us before returing from attach,
which caused `attach` to be slow. This commit implements proper
signal checking to verify if the attached process indeed stopped, or
died for some other reason.
Closes #52

Implement proper ptrace wait signal handling

---

tools/ptrace.c

Use a self-growing array instead of ptracing the string twice.

Refactor read_string

---

tools/introspection.c
tools/introspection.h

Implement verification that all threads have been correctly hijacked in critical section functions.

Implement critical section verification #25

---

lib/interpose.c

OpenSUSE tumbleweed updated to glibc 2.34, which moved libdl symbols
into libc.so itself. Fix that by looking into libc.so as well for the
wanted symbols.

Fix compatibility with glibc 2.34

---

tools/ulp.c

Trigger requires -p. Update help message accordingly.
Closes #64 
Signed-off-by: Giuliano Belinassi <giulianob@localhost.localdomain>

Fix help command info about -p

---

Makefile.am
common/Makefile.am
common/common.c
configure.ac
include/ulp_common.h
lib/Makefile.am
lib/ulp.c
tools/Makefile.am
tools/ulp.c

Add a `common` folder where code common among `tools` and `lib` can sit.

Common refactor

---

tools/packer.c

In C, a string is defined as an array of characters terminated with the
null character '\0' (K&R The C Programming Language, 1988). This means
that the length of the empty string, which is 0, has size 1 because it
must contain the '\0' character. Induction on the length of the string
shows that the size of the string is its length + 1.
This means we should write to the metadata file the string size as being
its length + 1 to account for the string size. Else the read strings on
trigger may not end which the '\0' character.

Fix metadata string szies

---

common/common.c
include/Makefile.am
include/error.h
include/error_common.h
lib/error.c
lib/ulp.c
tools/check.c
tools/introspection.c
tools/ptrace.c
tools/trigger.c

Implements errorcodes in libpulp.
Closes #58

Errorcodes

---

tests/deadlock.py

Deadlock testcase could fail depending of CPU usage because there is 
no way to detect if the program is unlocked. There is no way to solve
this issue generally (i.e. it is equivalent to the halting problem), so
only fails if trigger indeed deadlocks and never returns, exposing a
deadlock in libpulp. If all attempts failed it should still be a
success because it isn't a deadlocks.

Fix deadlock testcase

---

configure.ac

Bump version to 0.2.1

---

configure.ac

Bump version to 0.2.2

---

tools/introspection.c
tools/patches.c
tools/ptrace.c
tools/ptrace.h
tools/ulp.c

Set a timeout timer If for some reason trigger deadlocks in libpulp.

Add timeout to trigger

---

scripts/setup_package.sh

The debuginfo is useful for checking if inlined symbol is still available on target binary, hence the livepatch developer may want it.

Update setup_package.sh to download debuginfo

---

lib/msg_queue.c
tools/introspection.c

This should help debugging test problems.

Add timestamp to WARN and DEBUG messages

---

tests/Makefile.am
tests/libnotes_livepatch1.c
tests/libnotes_livepatch1.in
tests/notes.c
tests/notes.ld
tests/notes.py
tools/introspection.c

See each commit message for a detailed description.

Fix bug in processing of NOTES headers

---

lib/arch/powerpc64le/ulp_prologue.S

This include some comment fix as well as some drawings to picture the status of the ulp_stack during the process.
@dubeyabhishek can you take a look on this?

Improve comments ulp_prologue.S in ppc64le port.

---

lib/arch/powerpc64le/patch.c

On the ppc64le port of libpulp, a special stack is necessary to hold information between redirections.  The original implementation called memcpy two times, one when the DEBUG macro is expanded and another when the ulp_stack overflows and a new stack is allocated.
Hence, avoid this problem by not calling memcpy in this site.

Fix libpulp not able to livepatch memcpy on ppc64le
